name: Mypy

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Mypy
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
    - name: Install Dependencies
      run: |
        pip install mypy
    - name: mypy
      run: |
        mypy optika/
